//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIBusiness.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptsGYMDB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptsGYMDB() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAPIBusiness.Resources.ScriptsGYMDB", typeof(ScriptsGYMDB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a --CONSULTA CLASES DE DISCIPLINA EN UNA FECHA 
        ///SELECT 
        ///CR.fecha,
        ///HM.horaInicio,
        ///HM.horaFin,
        ///CL.nombre,
        ///CL.descripcion
        ///FROM cronograma CR
        ///INNER JOIN horarioM HM ON CR.horarioMID = HM.horarioMID
        ///INNER JOIN clase CL ON CR.claseID = CL.claseID
        ///INNER JOIN sala S ON CR.salaID = S.salaID
        ///INNER JOIN clase_persona CLP ON CR.claseID = CLP.claseID
        ///WHERE CL.disciplinaID in (
        ///SELECT disciplinaID FROM membresia_persona_disciplina WHERE personaID = &apos;1&apos; AND status = &apos;A&apos;
        ///)
        ///AND CR.fecha = &apos;2021-09-11&apos;
        ///AND CLP. [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string getClasesDisicplinaFecha {
            get {
                return ResourceManager.GetString("getClasesDisicplinaFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT DISTINCT HM.horarioMID ,HM.horaInicio,HM.horaFin FROM clase CL
        ///INNER JOIN cronograma CR ON CR.cronogramaID = CL.cronogramaID
        ///INNER JOIN horarioM HM ON HM.horarioMID = CR.horarioMID
        ///WHERE CL.disciplinaID = &apos;&apos;.
        /// </summary>
        internal static string getHorasDisciplina {
            get {
                return ResourceManager.GetString("getHorasDisciplina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///D.disciplinaID,
        ///D.nombre as nombreDisciplina,
        ///M.precio,
        ///MPD.numClasesDisponibles,
        ///--MPD.fechaPago,
        ///--MPD.fechaLimite,
        ///M.nombre as nombreMembresia
        ///FROM membresia_persona_disciplina MPD
        ///INNER JOIN membresia M ON M.membresiaID = MPD.membresiaID 
        ///INNER JOIN disciplina D ON D.disciplinaID = MPD.disciplinaID
        ///WHERE MPD.personaID = {0}.
        /// </summary>
        internal static string getMembresiasUsuario {
            get {
                return ResourceManager.GetString("getMembresiasUsuario", resourceCulture);
            }
        }
    }
}
