//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIBusiness.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptsGYMDB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptsGYMDB() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAPIBusiness.Resources.ScriptsGYMDB", typeof(ScriptsGYMDB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT HM.horarioMID ,HM.horaInicio,HM.horaFin FROM clase CL
        ///INNER JOIN cronograma CR ON CR.cronogramaID = CL.cronogramaID
        ///INNER JOIN horarioM HM ON HM.horarioMID = CR.horarioMID
        ///WHERE CL.disciplinaID = &apos;&apos;.
        /// </summary>
        internal static string getHorasDisciplina {
            get {
                return ResourceManager.GetString("getHorasDisciplina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///D.disciplinaID,
        ///D.nombre as nombreDisciplina,
        ///M.precio,
        ///MPD.numClasesDisponibles,
        ///MPD.fechaPago,
        ///MPD.fechaLimite,
        ///M.nombre as nombreMembresia
        ///FROM membresia_persona_disciplina MPD
        ///INNER JOIN membresia M ON M.membresiaID = MPD.membresiaID 
        ///INNER JOIN disciplina D ON D.disciplinaID = MPD.disciplinaID
        ///WHERE MPD.personaID = {0}.
        /// </summary>
        internal static string getMembresiasUsuario {
            get {
                return ResourceManager.GetString("getMembresiasUsuario", resourceCulture);
            }
        }
    }
}
