//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIData
{
    using System;
    using System.Collections.Generic;
    
    public partial class clase_recurso
    {
        public int clase_recursoID { get; set; }
        public int claseID { get; set; }
        public int recursoID { get; set; }
        public int reservado { get; set; }
        public Nullable<int> personaID { get; set; }
    
        public virtual clase clase { get; set; }
        public virtual persona persona { get; set; }
        public virtual recurso recurso { get; set; }
    }
}
