//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIData
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento_recurso
    {
        public int evento_recursoID { get; set; }
        public int eventoID { get; set; }
        public int recursoID { get; set; }
        public int cantidadRecurso { get; set; }
    
        public virtual evento evento { get; set; }
        public virtual recurso recurso { get; set; }
    }
}
