//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIData
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento_profesor
    {
        public int evento_profesorID { get; set; }
        public int eventoID { get; set; }
        public int personaID { get; set; }
        public int asistencia { get; set; }
        public string estadoRegistro { get; set; }
        public string motivo { get; set; }
        public string posibleHorarioRecuperacion { get; set; }
    }
}
