//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIData
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento_recursoEspecial
    {
        public int evento_recursoEspecialID { get; set; }
        public int eventoID { get; set; }
        public int recursoEspecialID { get; set; }
        public Nullable<int> personaID { get; set; }
    
        public virtual evento evento { get; set; }
        public virtual recursoEspecial recursoEspecial { get; set; }
    }
}
