//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIData
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento_recurso
    {
        public int evento_recursoID { get; set; }
        public int eventoID { get; set; }
        public int recursoID { get; set; }
        public int cantidadRecurso { get; set; }
    
        public virtual evento evento { get; set; }
        public virtual recurso recurso { get; set; }
    }
}
