//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIData
{
    using System;
    using System.Collections.Generic;
    
    public partial class membresia_persona_pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public membresia_persona_pago()
        {
            this.membresia_persona_disciplina = new HashSet<membresia_persona_disciplina>();
            this.sol_membresiaPago = new HashSet<sol_membresiaPago>();
        }
    
        public int membresia_persona_pagoID { get; set; }
        public int personaID { get; set; }
        public int membresiaID { get; set; }
        public System.DateTime fechaInicioMembresia { get; set; }
        public System.DateTime fechaFinMembresia { get; set; }
        public string formaPago { get; set; }
        public Nullable<System.DateTime> fechaTransaccion { get; set; }
        public string nroDocumento { get; set; }
        public string Banco { get; set; }
        public string estado { get; set; }
    
        public virtual membresia membresia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<membresia_persona_disciplina> membresia_persona_disciplina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sol_membresiaPago> sol_membresiaPago { get; set; }
        public virtual persona persona { get; set; }
    }
}
