//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIData
{
    using System;
    using System.Collections.Generic;
    
    public partial class membresia_persona_pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public membresia_persona_pago()
        {
            this.solicitud_membresiaPersona = new HashSet<solicitud_membresiaPersona>();
        }
    
        public int membresia_persona_pagoID { get; set; }
        public int personaID { get; set; }
        public int membresiaID { get; set; }
        public System.DateTime fechaInicioMembresia { get; set; }
        public System.DateTime fechaFinMembresia { get; set; }
        public string formaPago { get; set; }
        public System.DateTime fechaTransaccion { get; set; }
        public string nroDocumento { get; set; }
        public string tipoBanco { get; set; }
        public string estado { get; set; }
    
        public virtual membresia membresia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<solicitud_membresiaPersona> solicitud_membresiaPersona { get; set; }
        public virtual persona persona { get; set; }
    }
}
