//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIData
{
    using System;
    using System.Collections.Generic;
    
    public partial class membresia_disciplina
    {
        public int membresia_discplinaID { get; set; }
        public int membresiaID { get; set; }
        public int disciplinaID { get; set; }
    
        public virtual disciplina disciplina { get; set; }
        public virtual membresia membresia { get; set; }
    }
}
