//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIData
{
    using System;
    using System.Collections.Generic;
    
    public partial class membresia_persona
    {
        public int membresia_personaID { get; set; }
        public int personaID { get; set; }
        public int membresiaID { get; set; }
        public int numReservas { get; set; }
    
        public virtual membresia membresia { get; set; }
        public virtual persona persona { get; set; }
    }
}
