//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIData
{
    using System;
    using System.Collections.Generic;
    
    public partial class recurso
    {
        public int recursoID { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int cantidadRecurso { get; set; }
        public string estadoRegistro { get; set; }
    }
}
