//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaRecurso
    {
        public int salaRecursoID { get; set; }
        public int salaID { get; set; }
        public string nombreRecurso { get; set; }
        public int cantidad { get; set; }
    
        public virtual sala sala { get; set; }
    }
}
