//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIData
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int usuarioID { get; set; }
        public int personaID { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    
        public virtual persona persona { get; set; }
    }
}
